version: '3'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - db:${PGDATA}
    environment:
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
          - POSTGRES_USER=${POSTGRES_USER}
          - POSTGRES_DB=${POSTGRES_DB}
          - PGDATA=${PGDATA}

  backend:
    image: backend
    restart: always
    depends_on: 
      - db
    ports:
      - 80:8080
    build:
      context: ./
      dockerfile: Dockerfile
   
volumes:
  db: