version: '3'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
          - POSTGRES_PASSWORD=password
          - POSTGRES_USER=postgres
          - POSTGRES_DB=attendance
          - PGDATA=/var/lib/pgsql/data

  adminer:
      image: adminer
      restart: always
      ports:
        - 8000:8080
