version: '3'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
          - POSTGRES_PASSWORD: password
          - POSTGRES_USER: postgres
          - POSTGRES_DB: attendance
          - PGDATA: /var/lib/pgsql/data
    volumes:
      - db: ${PGDATA}

  backend:
    image: backend
    restart: always
    depends_on: 
      - db
    ports:
      - 80:8080
    build:
      context: ./
      dockerfile: Dockerfile
   
volumes:
  db: